eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/
server:
  port: 8775
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
feign:
    hystrix:
      enabled: true #Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码
turbine:
  aggregator:
    clusterConfig: SERVICE-1
  appConfig: service-1   #SERVICE-1,SERVICE-2