spring:
  application.name: service-turbine
server:
  port: 8999
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig:  default   #SERVICE-FEIGN
  appConfig: service-feign,service-1,service-ribbon,service-zuul
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/